// flow-typed signature: ae3ebf8b42370395be0a6a70ea3cc68c
// flow-typed version: <<STUB>>/bs-platform_v^5.0.5-beta.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-platform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-platform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-platform/lib/es6/arg' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/arrayLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Debug' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashMap' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashSet' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_HashSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Id' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Int' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalAVLset' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalAVLtree' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalBuckets' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalBucketsType' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalSetBuckets' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_internalSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_List' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Map' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MapDict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableMap' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableQueue' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableSet' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_MutableStack' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Range' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Result' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_Set' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SetDict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SortArray' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SortArrayInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt_SortArrayString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/belt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/bigarray' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/block' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/buffer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/bytes' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/bytesLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/callback' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_array_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_builtin_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_bytes_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_bytes' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_char' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_chrome_debugger' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_float_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_format' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_gc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_hash_primitive' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_hash' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_int32_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_int32' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_int64_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_int64' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_io' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_js_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_lexer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_md5' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_missing_polyfill' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_module' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_nativeint_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_obj_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_oo_curry' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_oo' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_parser' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_primitive' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_splice_call' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_string_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_sys' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_undefined_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_utils' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/caml_weak' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/camlinternalFormat' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/camlinternalFormatBasics' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/camlinternalLazy' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/camlinternalMod' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/camlinternalOO' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/char' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/complex' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/curry' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/digest' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/dom_storage' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/dom_storage2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/dom' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/filename' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/format' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/gc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/genlex' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/hashtbl' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/int32' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/int64' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_array2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_cast' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_console' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_date' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_dict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_exn' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_global' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_int' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_json' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_list' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_mapperRt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_math' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_null_undefined' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_null' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_promise' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_re' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_result' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_string2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_typed_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_typed_array2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_types' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_undefined' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js_vector' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/js' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/lazy' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/lexing' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/list' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/listLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/map' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/marshal' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/moreLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/nativeint' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_buffer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_child_process' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_fs' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_module' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_path' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node_process' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/node' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/oo' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/parsing' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/pervasives' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/printexc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/printf' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/queue' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/random' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/scanf' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/set' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/sort' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/stack' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/std_exit' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/stdLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/stream' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/stringLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/sys' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/unix' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/unixLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/es6/weak' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/arg' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/arrayLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Debug' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashMap' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashSet' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_HashSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Id' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Int' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalAVLset' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalAVLtree' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalBuckets' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalBucketsType' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalSetBuckets' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_internalSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_List' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Map' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MapDict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableMap' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableMapInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableMapString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableQueue' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableSet' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableSetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableSetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_MutableStack' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Range' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Result' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_Set' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SetDict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SetInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SetString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SortArray' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SortArrayInt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt_SortArrayString' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/belt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/bigarray' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/block' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/buffer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/bytes' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/bytesLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/callback' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_array_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_builtin_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_bytes_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_bytes' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_char' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_chrome_debugger' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_float_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_format' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_gc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_hash_primitive' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_hash' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_int32_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_int32' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_int64_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_int64' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_io' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_js_exceptions' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_lexer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_md5' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_missing_polyfill' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_module' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_nativeint_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_obj_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_oo_curry' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_oo' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_parser' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_primitive' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_splice_call' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_string_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_sys' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_undefined_extern' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_utils' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/caml_weak' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalBigarray' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalFormat' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalFormatBasics' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalLazy' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalMod' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/camlinternalOO' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/char' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/complex' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/curry' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/digest' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/dom_storage' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/dom_storage2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/dom' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/ephemeron' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/filename' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/format' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/gc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/genlex' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/hashtbl' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/int32' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/int64' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_array2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_cast' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_console' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_date' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_dict' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_exn' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_float' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_global' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_int' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_json' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_list' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_mapperRt' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_math' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_null_undefined' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_null' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_option' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_promise' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_promise2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_re' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_result' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_string2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_typed_array' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_typed_array2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_types' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_undefined' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js_vector' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/js' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/lazy' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/lexing' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/list' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/listLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/map' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/marshal' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/moreLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/nativeint' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_buffer' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_child_process' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_fs' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_fs2' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_module' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_path' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node_process' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/node' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/obj' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/oo' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/parsing' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/pervasives' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/printexc' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/printf' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/queue' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/random' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/scanf' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/set' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/sort' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/spacetime' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/stack' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/std_exit' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/stdLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/stream' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/string' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/stringLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/sys' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/uchar' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/unix' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/unixLabels' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/js/weak' {
  declare module.exports: any;
}

declare module 'bs-platform/lib/minisocket' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/buildocaml' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/ciTest' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/config' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/dedupe' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/doc_gen' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/install' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/js_internal_gen' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/ninja' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/ninjaFactory' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/prebuilt' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/prepublish' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/release' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/repl' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/tasks' {
  declare module.exports: any;
}

declare module 'bs-platform/scripts/tmp' {
  declare module.exports: any;
}

declare module 'bs-platform/vendor/rollup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-platform/lib/es6/arg.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/arg'>;
}
declare module 'bs-platform/lib/es6/array.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/array'>;
}
declare module 'bs-platform/lib/es6/arrayLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/arrayLabels'>;
}
declare module 'bs-platform/lib/es6/belt_Array.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Array'>;
}
declare module 'bs-platform/lib/es6/belt_Debug.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Debug'>;
}
declare module 'bs-platform/lib/es6/belt_Float.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Float'>;
}
declare module 'bs-platform/lib/es6/belt_HashMap.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashMap'>;
}
declare module 'bs-platform/lib/es6/belt_HashMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashMapInt'>;
}
declare module 'bs-platform/lib/es6/belt_HashMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashMapString'>;
}
declare module 'bs-platform/lib/es6/belt_HashSet.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashSet'>;
}
declare module 'bs-platform/lib/es6/belt_HashSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashSetInt'>;
}
declare module 'bs-platform/lib/es6/belt_HashSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_HashSetString'>;
}
declare module 'bs-platform/lib/es6/belt_Id.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Id'>;
}
declare module 'bs-platform/lib/es6/belt_Int.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Int'>;
}
declare module 'bs-platform/lib/es6/belt_internalAVLset.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalAVLset'>;
}
declare module 'bs-platform/lib/es6/belt_internalAVLtree.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalAVLtree'>;
}
declare module 'bs-platform/lib/es6/belt_internalBuckets.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalBuckets'>;
}
declare module 'bs-platform/lib/es6/belt_internalBucketsType.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalBucketsType'>;
}
declare module 'bs-platform/lib/es6/belt_internalMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalMapInt'>;
}
declare module 'bs-platform/lib/es6/belt_internalMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalMapString'>;
}
declare module 'bs-platform/lib/es6/belt_internalSetBuckets.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalSetBuckets'>;
}
declare module 'bs-platform/lib/es6/belt_internalSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalSetInt'>;
}
declare module 'bs-platform/lib/es6/belt_internalSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_internalSetString'>;
}
declare module 'bs-platform/lib/es6/belt_List.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_List'>;
}
declare module 'bs-platform/lib/es6/belt_Map.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Map'>;
}
declare module 'bs-platform/lib/es6/belt_MapDict.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MapDict'>;
}
declare module 'bs-platform/lib/es6/belt_MapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MapInt'>;
}
declare module 'bs-platform/lib/es6/belt_MapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MapString'>;
}
declare module 'bs-platform/lib/es6/belt_MutableMap.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableMap'>;
}
declare module 'bs-platform/lib/es6/belt_MutableMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableMapInt'>;
}
declare module 'bs-platform/lib/es6/belt_MutableMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableMapString'>;
}
declare module 'bs-platform/lib/es6/belt_MutableQueue.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableQueue'>;
}
declare module 'bs-platform/lib/es6/belt_MutableSet.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableSet'>;
}
declare module 'bs-platform/lib/es6/belt_MutableSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableSetInt'>;
}
declare module 'bs-platform/lib/es6/belt_MutableSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableSetString'>;
}
declare module 'bs-platform/lib/es6/belt_MutableStack.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_MutableStack'>;
}
declare module 'bs-platform/lib/es6/belt_Option.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Option'>;
}
declare module 'bs-platform/lib/es6/belt_Range.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Range'>;
}
declare module 'bs-platform/lib/es6/belt_Result.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Result'>;
}
declare module 'bs-platform/lib/es6/belt_Set.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_Set'>;
}
declare module 'bs-platform/lib/es6/belt_SetDict.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SetDict'>;
}
declare module 'bs-platform/lib/es6/belt_SetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SetInt'>;
}
declare module 'bs-platform/lib/es6/belt_SetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SetString'>;
}
declare module 'bs-platform/lib/es6/belt_SortArray.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SortArray'>;
}
declare module 'bs-platform/lib/es6/belt_SortArrayInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SortArrayInt'>;
}
declare module 'bs-platform/lib/es6/belt_SortArrayString.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt_SortArrayString'>;
}
declare module 'bs-platform/lib/es6/belt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/belt'>;
}
declare module 'bs-platform/lib/es6/bigarray.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/bigarray'>;
}
declare module 'bs-platform/lib/es6/block.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/block'>;
}
declare module 'bs-platform/lib/es6/buffer.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/buffer'>;
}
declare module 'bs-platform/lib/es6/bytes.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/bytes'>;
}
declare module 'bs-platform/lib/es6/bytesLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/bytesLabels'>;
}
declare module 'bs-platform/lib/es6/callback.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/callback'>;
}
declare module 'bs-platform/lib/es6/caml_array_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_array_extern'>;
}
declare module 'bs-platform/lib/es6/caml_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_array'>;
}
declare module 'bs-platform/lib/es6/caml_builtin_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_builtin_exceptions'>;
}
declare module 'bs-platform/lib/es6/caml_bytes_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_bytes_extern'>;
}
declare module 'bs-platform/lib/es6/caml_bytes.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_bytes'>;
}
declare module 'bs-platform/lib/es6/caml_char.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_char'>;
}
declare module 'bs-platform/lib/es6/caml_chrome_debugger.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_chrome_debugger'>;
}
declare module 'bs-platform/lib/es6/caml_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_exceptions'>;
}
declare module 'bs-platform/lib/es6/caml_float_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_float_extern'>;
}
declare module 'bs-platform/lib/es6/caml_float.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_float'>;
}
declare module 'bs-platform/lib/es6/caml_format.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_format'>;
}
declare module 'bs-platform/lib/es6/caml_gc.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_gc'>;
}
declare module 'bs-platform/lib/es6/caml_hash_primitive.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_hash_primitive'>;
}
declare module 'bs-platform/lib/es6/caml_hash.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_hash'>;
}
declare module 'bs-platform/lib/es6/caml_int32_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_int32_extern'>;
}
declare module 'bs-platform/lib/es6/caml_int32.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_int32'>;
}
declare module 'bs-platform/lib/es6/caml_int64_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_int64_extern'>;
}
declare module 'bs-platform/lib/es6/caml_int64.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_int64'>;
}
declare module 'bs-platform/lib/es6/caml_io.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_io'>;
}
declare module 'bs-platform/lib/es6/caml_js_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_js_exceptions'>;
}
declare module 'bs-platform/lib/es6/caml_lexer.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_lexer'>;
}
declare module 'bs-platform/lib/es6/caml_md5.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_md5'>;
}
declare module 'bs-platform/lib/es6/caml_missing_polyfill.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_missing_polyfill'>;
}
declare module 'bs-platform/lib/es6/caml_module.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_module'>;
}
declare module 'bs-platform/lib/es6/caml_nativeint_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_nativeint_extern'>;
}
declare module 'bs-platform/lib/es6/caml_obj_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_obj_extern'>;
}
declare module 'bs-platform/lib/es6/caml_obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_obj'>;
}
declare module 'bs-platform/lib/es6/caml_oo_curry.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_oo_curry'>;
}
declare module 'bs-platform/lib/es6/caml_oo.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_oo'>;
}
declare module 'bs-platform/lib/es6/caml_option.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_option'>;
}
declare module 'bs-platform/lib/es6/caml_parser.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_parser'>;
}
declare module 'bs-platform/lib/es6/caml_primitive.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_primitive'>;
}
declare module 'bs-platform/lib/es6/caml_splice_call.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_splice_call'>;
}
declare module 'bs-platform/lib/es6/caml_string_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_string_extern'>;
}
declare module 'bs-platform/lib/es6/caml_string.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_string'>;
}
declare module 'bs-platform/lib/es6/caml_sys.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_sys'>;
}
declare module 'bs-platform/lib/es6/caml_undefined_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_undefined_extern'>;
}
declare module 'bs-platform/lib/es6/caml_utils.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_utils'>;
}
declare module 'bs-platform/lib/es6/caml_weak.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/caml_weak'>;
}
declare module 'bs-platform/lib/es6/camlinternalFormat.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/camlinternalFormat'>;
}
declare module 'bs-platform/lib/es6/camlinternalFormatBasics.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/camlinternalFormatBasics'>;
}
declare module 'bs-platform/lib/es6/camlinternalLazy.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/camlinternalLazy'>;
}
declare module 'bs-platform/lib/es6/camlinternalMod.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/camlinternalMod'>;
}
declare module 'bs-platform/lib/es6/camlinternalOO.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/camlinternalOO'>;
}
declare module 'bs-platform/lib/es6/char.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/char'>;
}
declare module 'bs-platform/lib/es6/complex.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/complex'>;
}
declare module 'bs-platform/lib/es6/curry.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/curry'>;
}
declare module 'bs-platform/lib/es6/digest.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/digest'>;
}
declare module 'bs-platform/lib/es6/dom_storage.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/dom_storage'>;
}
declare module 'bs-platform/lib/es6/dom_storage2.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/dom_storage2'>;
}
declare module 'bs-platform/lib/es6/dom.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/dom'>;
}
declare module 'bs-platform/lib/es6/filename.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/filename'>;
}
declare module 'bs-platform/lib/es6/format.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/format'>;
}
declare module 'bs-platform/lib/es6/gc.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/gc'>;
}
declare module 'bs-platform/lib/es6/genlex.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/genlex'>;
}
declare module 'bs-platform/lib/es6/hashtbl.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/hashtbl'>;
}
declare module 'bs-platform/lib/es6/int32.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/int32'>;
}
declare module 'bs-platform/lib/es6/int64.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/int64'>;
}
declare module 'bs-platform/lib/es6/js_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_array'>;
}
declare module 'bs-platform/lib/es6/js_array2.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_array2'>;
}
declare module 'bs-platform/lib/es6/js_cast.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_cast'>;
}
declare module 'bs-platform/lib/es6/js_console.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_console'>;
}
declare module 'bs-platform/lib/es6/js_date.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_date'>;
}
declare module 'bs-platform/lib/es6/js_dict.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_dict'>;
}
declare module 'bs-platform/lib/es6/js_exn.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_exn'>;
}
declare module 'bs-platform/lib/es6/js_float.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_float'>;
}
declare module 'bs-platform/lib/es6/js_global.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_global'>;
}
declare module 'bs-platform/lib/es6/js_int.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_int'>;
}
declare module 'bs-platform/lib/es6/js_json.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_json'>;
}
declare module 'bs-platform/lib/es6/js_list.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_list'>;
}
declare module 'bs-platform/lib/es6/js_mapperRt.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_mapperRt'>;
}
declare module 'bs-platform/lib/es6/js_math.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_math'>;
}
declare module 'bs-platform/lib/es6/js_null_undefined.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_null_undefined'>;
}
declare module 'bs-platform/lib/es6/js_null.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_null'>;
}
declare module 'bs-platform/lib/es6/js_obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_obj'>;
}
declare module 'bs-platform/lib/es6/js_option.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_option'>;
}
declare module 'bs-platform/lib/es6/js_promise.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_promise'>;
}
declare module 'bs-platform/lib/es6/js_re.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_re'>;
}
declare module 'bs-platform/lib/es6/js_result.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_result'>;
}
declare module 'bs-platform/lib/es6/js_string.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_string'>;
}
declare module 'bs-platform/lib/es6/js_string2.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_string2'>;
}
declare module 'bs-platform/lib/es6/js_typed_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_typed_array'>;
}
declare module 'bs-platform/lib/es6/js_typed_array2.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_typed_array2'>;
}
declare module 'bs-platform/lib/es6/js_types.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_types'>;
}
declare module 'bs-platform/lib/es6/js_undefined.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_undefined'>;
}
declare module 'bs-platform/lib/es6/js_vector.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js_vector'>;
}
declare module 'bs-platform/lib/es6/js.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/js'>;
}
declare module 'bs-platform/lib/es6/lazy.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/lazy'>;
}
declare module 'bs-platform/lib/es6/lexing.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/lexing'>;
}
declare module 'bs-platform/lib/es6/list.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/list'>;
}
declare module 'bs-platform/lib/es6/listLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/listLabels'>;
}
declare module 'bs-platform/lib/es6/map.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/map'>;
}
declare module 'bs-platform/lib/es6/marshal.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/marshal'>;
}
declare module 'bs-platform/lib/es6/moreLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/moreLabels'>;
}
declare module 'bs-platform/lib/es6/nativeint.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/nativeint'>;
}
declare module 'bs-platform/lib/es6/node_buffer.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_buffer'>;
}
declare module 'bs-platform/lib/es6/node_child_process.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_child_process'>;
}
declare module 'bs-platform/lib/es6/node_fs.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_fs'>;
}
declare module 'bs-platform/lib/es6/node_module.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_module'>;
}
declare module 'bs-platform/lib/es6/node_path.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_path'>;
}
declare module 'bs-platform/lib/es6/node_process.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node_process'>;
}
declare module 'bs-platform/lib/es6/node.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/node'>;
}
declare module 'bs-platform/lib/es6/obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/obj'>;
}
declare module 'bs-platform/lib/es6/oo.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/oo'>;
}
declare module 'bs-platform/lib/es6/parsing.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/parsing'>;
}
declare module 'bs-platform/lib/es6/pervasives.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/pervasives'>;
}
declare module 'bs-platform/lib/es6/printexc.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/printexc'>;
}
declare module 'bs-platform/lib/es6/printf.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/printf'>;
}
declare module 'bs-platform/lib/es6/queue.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/queue'>;
}
declare module 'bs-platform/lib/es6/random.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/random'>;
}
declare module 'bs-platform/lib/es6/scanf.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/scanf'>;
}
declare module 'bs-platform/lib/es6/set.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/set'>;
}
declare module 'bs-platform/lib/es6/sort.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/sort'>;
}
declare module 'bs-platform/lib/es6/stack.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/stack'>;
}
declare module 'bs-platform/lib/es6/std_exit.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/std_exit'>;
}
declare module 'bs-platform/lib/es6/stdLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/stdLabels'>;
}
declare module 'bs-platform/lib/es6/stream.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/stream'>;
}
declare module 'bs-platform/lib/es6/string.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/string'>;
}
declare module 'bs-platform/lib/es6/stringLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/stringLabels'>;
}
declare module 'bs-platform/lib/es6/sys.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/sys'>;
}
declare module 'bs-platform/lib/es6/unix.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/unix'>;
}
declare module 'bs-platform/lib/es6/unixLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/unixLabels'>;
}
declare module 'bs-platform/lib/es6/weak.js' {
  declare module.exports: $Exports<'bs-platform/lib/es6/weak'>;
}
declare module 'bs-platform/lib/js/arg.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/arg'>;
}
declare module 'bs-platform/lib/js/array.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/array'>;
}
declare module 'bs-platform/lib/js/arrayLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/arrayLabels'>;
}
declare module 'bs-platform/lib/js/belt_Array.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Array'>;
}
declare module 'bs-platform/lib/js/belt_Debug.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Debug'>;
}
declare module 'bs-platform/lib/js/belt_Float.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Float'>;
}
declare module 'bs-platform/lib/js/belt_HashMap.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashMap'>;
}
declare module 'bs-platform/lib/js/belt_HashMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashMapInt'>;
}
declare module 'bs-platform/lib/js/belt_HashMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashMapString'>;
}
declare module 'bs-platform/lib/js/belt_HashSet.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashSet'>;
}
declare module 'bs-platform/lib/js/belt_HashSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashSetInt'>;
}
declare module 'bs-platform/lib/js/belt_HashSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_HashSetString'>;
}
declare module 'bs-platform/lib/js/belt_Id.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Id'>;
}
declare module 'bs-platform/lib/js/belt_Int.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Int'>;
}
declare module 'bs-platform/lib/js/belt_internalAVLset.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalAVLset'>;
}
declare module 'bs-platform/lib/js/belt_internalAVLtree.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalAVLtree'>;
}
declare module 'bs-platform/lib/js/belt_internalBuckets.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalBuckets'>;
}
declare module 'bs-platform/lib/js/belt_internalBucketsType.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalBucketsType'>;
}
declare module 'bs-platform/lib/js/belt_internalMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalMapInt'>;
}
declare module 'bs-platform/lib/js/belt_internalMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalMapString'>;
}
declare module 'bs-platform/lib/js/belt_internalSetBuckets.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalSetBuckets'>;
}
declare module 'bs-platform/lib/js/belt_internalSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalSetInt'>;
}
declare module 'bs-platform/lib/js/belt_internalSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_internalSetString'>;
}
declare module 'bs-platform/lib/js/belt_List.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_List'>;
}
declare module 'bs-platform/lib/js/belt_Map.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Map'>;
}
declare module 'bs-platform/lib/js/belt_MapDict.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MapDict'>;
}
declare module 'bs-platform/lib/js/belt_MapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MapInt'>;
}
declare module 'bs-platform/lib/js/belt_MapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MapString'>;
}
declare module 'bs-platform/lib/js/belt_MutableMap.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableMap'>;
}
declare module 'bs-platform/lib/js/belt_MutableMapInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableMapInt'>;
}
declare module 'bs-platform/lib/js/belt_MutableMapString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableMapString'>;
}
declare module 'bs-platform/lib/js/belt_MutableQueue.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableQueue'>;
}
declare module 'bs-platform/lib/js/belt_MutableSet.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableSet'>;
}
declare module 'bs-platform/lib/js/belt_MutableSetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableSetInt'>;
}
declare module 'bs-platform/lib/js/belt_MutableSetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableSetString'>;
}
declare module 'bs-platform/lib/js/belt_MutableStack.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_MutableStack'>;
}
declare module 'bs-platform/lib/js/belt_Option.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Option'>;
}
declare module 'bs-platform/lib/js/belt_Range.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Range'>;
}
declare module 'bs-platform/lib/js/belt_Result.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Result'>;
}
declare module 'bs-platform/lib/js/belt_Set.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_Set'>;
}
declare module 'bs-platform/lib/js/belt_SetDict.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SetDict'>;
}
declare module 'bs-platform/lib/js/belt_SetInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SetInt'>;
}
declare module 'bs-platform/lib/js/belt_SetString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SetString'>;
}
declare module 'bs-platform/lib/js/belt_SortArray.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SortArray'>;
}
declare module 'bs-platform/lib/js/belt_SortArrayInt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SortArrayInt'>;
}
declare module 'bs-platform/lib/js/belt_SortArrayString.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt_SortArrayString'>;
}
declare module 'bs-platform/lib/js/belt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/belt'>;
}
declare module 'bs-platform/lib/js/bigarray.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/bigarray'>;
}
declare module 'bs-platform/lib/js/block.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/block'>;
}
declare module 'bs-platform/lib/js/buffer.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/buffer'>;
}
declare module 'bs-platform/lib/js/bytes.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/bytes'>;
}
declare module 'bs-platform/lib/js/bytesLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/bytesLabels'>;
}
declare module 'bs-platform/lib/js/callback.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/callback'>;
}
declare module 'bs-platform/lib/js/caml_array_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_array_extern'>;
}
declare module 'bs-platform/lib/js/caml_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_array'>;
}
declare module 'bs-platform/lib/js/caml_builtin_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_builtin_exceptions'>;
}
declare module 'bs-platform/lib/js/caml_bytes_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_bytes_extern'>;
}
declare module 'bs-platform/lib/js/caml_bytes.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_bytes'>;
}
declare module 'bs-platform/lib/js/caml_char.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_char'>;
}
declare module 'bs-platform/lib/js/caml_chrome_debugger.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_chrome_debugger'>;
}
declare module 'bs-platform/lib/js/caml_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_exceptions'>;
}
declare module 'bs-platform/lib/js/caml_float_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_float_extern'>;
}
declare module 'bs-platform/lib/js/caml_float.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_float'>;
}
declare module 'bs-platform/lib/js/caml_format.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_format'>;
}
declare module 'bs-platform/lib/js/caml_gc.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_gc'>;
}
declare module 'bs-platform/lib/js/caml_hash_primitive.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_hash_primitive'>;
}
declare module 'bs-platform/lib/js/caml_hash.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_hash'>;
}
declare module 'bs-platform/lib/js/caml_int32_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_int32_extern'>;
}
declare module 'bs-platform/lib/js/caml_int32.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_int32'>;
}
declare module 'bs-platform/lib/js/caml_int64_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_int64_extern'>;
}
declare module 'bs-platform/lib/js/caml_int64.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_int64'>;
}
declare module 'bs-platform/lib/js/caml_io.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_io'>;
}
declare module 'bs-platform/lib/js/caml_js_exceptions.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_js_exceptions'>;
}
declare module 'bs-platform/lib/js/caml_lexer.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_lexer'>;
}
declare module 'bs-platform/lib/js/caml_md5.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_md5'>;
}
declare module 'bs-platform/lib/js/caml_missing_polyfill.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_missing_polyfill'>;
}
declare module 'bs-platform/lib/js/caml_module.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_module'>;
}
declare module 'bs-platform/lib/js/caml_nativeint_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_nativeint_extern'>;
}
declare module 'bs-platform/lib/js/caml_obj_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_obj_extern'>;
}
declare module 'bs-platform/lib/js/caml_obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_obj'>;
}
declare module 'bs-platform/lib/js/caml_oo_curry.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_oo_curry'>;
}
declare module 'bs-platform/lib/js/caml_oo.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_oo'>;
}
declare module 'bs-platform/lib/js/caml_option.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_option'>;
}
declare module 'bs-platform/lib/js/caml_parser.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_parser'>;
}
declare module 'bs-platform/lib/js/caml_primitive.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_primitive'>;
}
declare module 'bs-platform/lib/js/caml_splice_call.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_splice_call'>;
}
declare module 'bs-platform/lib/js/caml_string_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_string_extern'>;
}
declare module 'bs-platform/lib/js/caml_string.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_string'>;
}
declare module 'bs-platform/lib/js/caml_sys.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_sys'>;
}
declare module 'bs-platform/lib/js/caml_undefined_extern.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_undefined_extern'>;
}
declare module 'bs-platform/lib/js/caml_utils.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_utils'>;
}
declare module 'bs-platform/lib/js/caml_weak.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/caml_weak'>;
}
declare module 'bs-platform/lib/js/camlinternalBigarray.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalBigarray'>;
}
declare module 'bs-platform/lib/js/camlinternalFormat.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalFormat'>;
}
declare module 'bs-platform/lib/js/camlinternalFormatBasics.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalFormatBasics'>;
}
declare module 'bs-platform/lib/js/camlinternalLazy.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalLazy'>;
}
declare module 'bs-platform/lib/js/camlinternalMod.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalMod'>;
}
declare module 'bs-platform/lib/js/camlinternalOO.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/camlinternalOO'>;
}
declare module 'bs-platform/lib/js/char.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/char'>;
}
declare module 'bs-platform/lib/js/complex.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/complex'>;
}
declare module 'bs-platform/lib/js/curry.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/curry'>;
}
declare module 'bs-platform/lib/js/digest.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/digest'>;
}
declare module 'bs-platform/lib/js/dom_storage.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/dom_storage'>;
}
declare module 'bs-platform/lib/js/dom_storage2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/dom_storage2'>;
}
declare module 'bs-platform/lib/js/dom.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/dom'>;
}
declare module 'bs-platform/lib/js/ephemeron.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/ephemeron'>;
}
declare module 'bs-platform/lib/js/filename.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/filename'>;
}
declare module 'bs-platform/lib/js/format.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/format'>;
}
declare module 'bs-platform/lib/js/gc.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/gc'>;
}
declare module 'bs-platform/lib/js/genlex.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/genlex'>;
}
declare module 'bs-platform/lib/js/hashtbl.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/hashtbl'>;
}
declare module 'bs-platform/lib/js/int32.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/int32'>;
}
declare module 'bs-platform/lib/js/int64.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/int64'>;
}
declare module 'bs-platform/lib/js/js_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_array'>;
}
declare module 'bs-platform/lib/js/js_array2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_array2'>;
}
declare module 'bs-platform/lib/js/js_cast.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_cast'>;
}
declare module 'bs-platform/lib/js/js_console.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_console'>;
}
declare module 'bs-platform/lib/js/js_date.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_date'>;
}
declare module 'bs-platform/lib/js/js_dict.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_dict'>;
}
declare module 'bs-platform/lib/js/js_exn.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_exn'>;
}
declare module 'bs-platform/lib/js/js_float.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_float'>;
}
declare module 'bs-platform/lib/js/js_global.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_global'>;
}
declare module 'bs-platform/lib/js/js_int.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_int'>;
}
declare module 'bs-platform/lib/js/js_json.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_json'>;
}
declare module 'bs-platform/lib/js/js_list.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_list'>;
}
declare module 'bs-platform/lib/js/js_mapperRt.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_mapperRt'>;
}
declare module 'bs-platform/lib/js/js_math.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_math'>;
}
declare module 'bs-platform/lib/js/js_null_undefined.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_null_undefined'>;
}
declare module 'bs-platform/lib/js/js_null.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_null'>;
}
declare module 'bs-platform/lib/js/js_obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_obj'>;
}
declare module 'bs-platform/lib/js/js_option.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_option'>;
}
declare module 'bs-platform/lib/js/js_promise.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_promise'>;
}
declare module 'bs-platform/lib/js/js_promise2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_promise2'>;
}
declare module 'bs-platform/lib/js/js_re.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_re'>;
}
declare module 'bs-platform/lib/js/js_result.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_result'>;
}
declare module 'bs-platform/lib/js/js_string.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_string'>;
}
declare module 'bs-platform/lib/js/js_string2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_string2'>;
}
declare module 'bs-platform/lib/js/js_typed_array.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_typed_array'>;
}
declare module 'bs-platform/lib/js/js_typed_array2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_typed_array2'>;
}
declare module 'bs-platform/lib/js/js_types.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_types'>;
}
declare module 'bs-platform/lib/js/js_undefined.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_undefined'>;
}
declare module 'bs-platform/lib/js/js_vector.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js_vector'>;
}
declare module 'bs-platform/lib/js/js.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/js'>;
}
declare module 'bs-platform/lib/js/lazy.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/lazy'>;
}
declare module 'bs-platform/lib/js/lexing.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/lexing'>;
}
declare module 'bs-platform/lib/js/list.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/list'>;
}
declare module 'bs-platform/lib/js/listLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/listLabels'>;
}
declare module 'bs-platform/lib/js/map.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/map'>;
}
declare module 'bs-platform/lib/js/marshal.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/marshal'>;
}
declare module 'bs-platform/lib/js/moreLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/moreLabels'>;
}
declare module 'bs-platform/lib/js/nativeint.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/nativeint'>;
}
declare module 'bs-platform/lib/js/node_buffer.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_buffer'>;
}
declare module 'bs-platform/lib/js/node_child_process.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_child_process'>;
}
declare module 'bs-platform/lib/js/node_fs.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_fs'>;
}
declare module 'bs-platform/lib/js/node_fs2.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_fs2'>;
}
declare module 'bs-platform/lib/js/node_module.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_module'>;
}
declare module 'bs-platform/lib/js/node_path.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_path'>;
}
declare module 'bs-platform/lib/js/node_process.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node_process'>;
}
declare module 'bs-platform/lib/js/node.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/node'>;
}
declare module 'bs-platform/lib/js/obj.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/obj'>;
}
declare module 'bs-platform/lib/js/oo.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/oo'>;
}
declare module 'bs-platform/lib/js/parsing.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/parsing'>;
}
declare module 'bs-platform/lib/js/pervasives.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/pervasives'>;
}
declare module 'bs-platform/lib/js/printexc.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/printexc'>;
}
declare module 'bs-platform/lib/js/printf.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/printf'>;
}
declare module 'bs-platform/lib/js/queue.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/queue'>;
}
declare module 'bs-platform/lib/js/random.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/random'>;
}
declare module 'bs-platform/lib/js/scanf.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/scanf'>;
}
declare module 'bs-platform/lib/js/set.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/set'>;
}
declare module 'bs-platform/lib/js/sort.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/sort'>;
}
declare module 'bs-platform/lib/js/spacetime.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/spacetime'>;
}
declare module 'bs-platform/lib/js/stack.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/stack'>;
}
declare module 'bs-platform/lib/js/std_exit.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/std_exit'>;
}
declare module 'bs-platform/lib/js/stdLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/stdLabels'>;
}
declare module 'bs-platform/lib/js/stream.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/stream'>;
}
declare module 'bs-platform/lib/js/string.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/string'>;
}
declare module 'bs-platform/lib/js/stringLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/stringLabels'>;
}
declare module 'bs-platform/lib/js/sys.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/sys'>;
}
declare module 'bs-platform/lib/js/uchar.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/uchar'>;
}
declare module 'bs-platform/lib/js/unix.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/unix'>;
}
declare module 'bs-platform/lib/js/unixLabels.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/unixLabels'>;
}
declare module 'bs-platform/lib/js/weak.js' {
  declare module.exports: $Exports<'bs-platform/lib/js/weak'>;
}
declare module 'bs-platform/lib/minisocket.js' {
  declare module.exports: $Exports<'bs-platform/lib/minisocket'>;
}
declare module 'bs-platform/scripts/buildocaml.js' {
  declare module.exports: $Exports<'bs-platform/scripts/buildocaml'>;
}
declare module 'bs-platform/scripts/ciTest.js' {
  declare module.exports: $Exports<'bs-platform/scripts/ciTest'>;
}
declare module 'bs-platform/scripts/config.js' {
  declare module.exports: $Exports<'bs-platform/scripts/config'>;
}
declare module 'bs-platform/scripts/dedupe.js' {
  declare module.exports: $Exports<'bs-platform/scripts/dedupe'>;
}
declare module 'bs-platform/scripts/doc_gen.js' {
  declare module.exports: $Exports<'bs-platform/scripts/doc_gen'>;
}
declare module 'bs-platform/scripts/install.js' {
  declare module.exports: $Exports<'bs-platform/scripts/install'>;
}
declare module 'bs-platform/scripts/js_internal_gen.js' {
  declare module.exports: $Exports<'bs-platform/scripts/js_internal_gen'>;
}
declare module 'bs-platform/scripts/ninja.js' {
  declare module.exports: $Exports<'bs-platform/scripts/ninja'>;
}
declare module 'bs-platform/scripts/ninjaFactory.js' {
  declare module.exports: $Exports<'bs-platform/scripts/ninjaFactory'>;
}
declare module 'bs-platform/scripts/prebuilt.js' {
  declare module.exports: $Exports<'bs-platform/scripts/prebuilt'>;
}
declare module 'bs-platform/scripts/prepublish.js' {
  declare module.exports: $Exports<'bs-platform/scripts/prepublish'>;
}
declare module 'bs-platform/scripts/release.js' {
  declare module.exports: $Exports<'bs-platform/scripts/release'>;
}
declare module 'bs-platform/scripts/repl.js' {
  declare module.exports: $Exports<'bs-platform/scripts/repl'>;
}
declare module 'bs-platform/scripts/tasks.js' {
  declare module.exports: $Exports<'bs-platform/scripts/tasks'>;
}
declare module 'bs-platform/scripts/tmp.js' {
  declare module.exports: $Exports<'bs-platform/scripts/tmp'>;
}
declare module 'bs-platform/vendor/rollup.js' {
  declare module.exports: $Exports<'bs-platform/vendor/rollup'>;
}
