// flow-typed signature: 64dad5091185ff73cfaaf966f216451c
// flow-typed version: <<STUB>>/reason_v^3.3.4/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reason'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reason' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reason/refmt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reason/refmt.js' {
  declare module.exports: $Exports<'reason/refmt'>;
}
