"use strict";
/* TypeScript file generated by genType. */
/* eslint-disable import/first */
Object.defineProperty(exports, "__esModule", { value: true });
// tslint:disable-next-line:no-var-requires
const CreateBucklescriptBlock = require('bs-platform/lib/es6/block.js');
// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');
// tslint:disable-next-line:no-var-requires
const TypesTransformerBS = require('./TypesTransformer.bs');
exports.printFromFlowTypes = function (Arg1) {
    const result = Curry._2(TypesTransformerBS.printFromFlowTypes, Arg1.content, Arg1.operationType.tag === "Fragment"
        ? CreateBucklescriptBlock.__(0, Arg1.operationType.value)
        : Arg1.operationType.tag === "Mutation"
            ? CreateBucklescriptBlock.__(1, [Arg1.operationType.value])
            : Arg1.operationType.tag === "Subscription"
                ? CreateBucklescriptBlock.__(2, [Arg1.operationType.value])
                : CreateBucklescriptBlock.__(3, [Arg1.operationType.value]));
    return result;
};
