// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE


function unwrap(wrapped) {
  switch (wrapped) {
    case "Discontinued" : 
        return /* Discontinued */293760815;
    case "Draft" : 
        return /* Draft */-219956991;
    case "Published" : 
        return /* Published */-358147186;
    default:
      return /* FUTURE_ADDED_VALUE__ */-769308010;
  }
}

function wrap(t) {
  if (t >= -219956991) {
    if (t >= 293760815) {
      return "Discontinued";
    } else {
      return "Draft";
    }
  } else if (t >= -358147186) {
    return "Published";
  } else {
    return "";
  }
}

var Enum_BookStatus = /* module */[
  /* unwrap */unwrap,
  /* wrap */wrap
];

function unwrap$1(wrapped) {
  switch (wrapped) {
    case "PRIVATE" : 
        return /* PRIVATE */155386083;
    case "PUBLIC" : 
        return /* PUBLIC */427175081;
    default:
      return /* FUTURE_ADDED_VALUE__ */-769308010;
  }
}

function wrap$1(t) {
  if (t !== 155386083) {
    if (t >= 427175081) {
      return "PUBLIC";
    } else {
      return "";
    }
  } else {
    return "PRIVATE";
  }
}

var Enum_CacheControlScope = /* module */[
  /* unwrap */unwrap$1,
  /* wrap */wrap$1
];

export {
  Enum_BookStatus ,
  Enum_CacheControlScope ,
  
}
/* No side effect */
