// Generated by BUCKLESCRIPT VERSION 5.0.5-beta.1, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Printer = require("./Printer.bs.js");

function makeScalarInt(param) {
  return /* Int */0;
}

function makeScalarString(param) {
  return /* String */1;
}

function makeScalarFloat(param) {
  return /* Float */2;
}

function makeScalarBoolean(param) {
  return /* Boolean */3;
}

function makeScalarCustom(identifier) {
  return /* CustomScalar */[identifier];
}

function makeScalarAny(param) {
  return /* Any */4;
}

function makePropScalar(scalarValue) {
  return /* Scalar */Block.__(0, [scalarValue]);
}

function makePropEnum(name) {
  return /* Enum */Block.__(1, [name]);
}

function makePropUnion(name) {
  return /* Union */Block.__(6, [name]);
}

function makePropObject(obj) {
  return /* Object */Block.__(2, [obj]);
}

function makePropArray(propValue) {
  return /* Array */Block.__(3, [propValue]);
}

function makeFragmentRefValue(name) {
  return /* FragmentRefValue */Block.__(4, [name]);
}

function makePropValue(nullable, propType, param) {
  return /* record */[
          /* nullable */nullable,
          /* propType */propType
        ];
}

function makeFragmentRefProp(name) {
  return /* FragmentRef */Block.__(0, [name]);
}

function makeObjProp(name, propValue, param) {
  return /* Prop */Block.__(1, [
            name,
            propValue
          ]);
}

function makeTypeReference(typeName) {
  return /* TypeReference */Block.__(5, [typeName]);
}

function makeObj(propValues) {
  return /* record */[/* values */propValues];
}

function makeOperation(definition) {
  return /* Operation */Block.__(0, [definition]);
}

function makeFragment(definition) {
  return /* Fragment */Block.__(1, [definition]);
}

function makePluralFragment(definition) {
  return /* PluralFragment */Block.__(4, [definition]);
}

function makeVariables(definition) {
  return /* Variables */Block.__(2, [definition]);
}

function makeStandaloneObjectType(definition) {
  return Printer.printObject(definition, /* JsNullable */0);
}

function makeInputObject(name, definition) {
  return /* InputObject */Block.__(3, [
            name,
            definition
          ]);
}

exports.makeScalarInt = makeScalarInt;
exports.makeScalarString = makeScalarString;
exports.makeScalarFloat = makeScalarFloat;
exports.makeScalarBoolean = makeScalarBoolean;
exports.makeScalarCustom = makeScalarCustom;
exports.makeScalarAny = makeScalarAny;
exports.makePropScalar = makePropScalar;
exports.makePropEnum = makePropEnum;
exports.makePropUnion = makePropUnion;
exports.makePropObject = makePropObject;
exports.makePropArray = makePropArray;
exports.makeFragmentRefValue = makeFragmentRefValue;
exports.makePropValue = makePropValue;
exports.makeFragmentRefProp = makeFragmentRefProp;
exports.makeObjProp = makeObjProp;
exports.makeTypeReference = makeTypeReference;
exports.makeObj = makeObj;
exports.makeOperation = makeOperation;
exports.makeFragment = makeFragment;
exports.makePluralFragment = makePluralFragment;
exports.makeVariables = makeVariables;
exports.makeStandaloneObjectType = makeStandaloneObjectType;
exports.makeInputObject = makeInputObject;
/* Printer Not a pure module */
