"use strict";
/* TypeScript file generated by genType. */
/* eslint-disable import/first */
Object.defineProperty(exports, "__esModule", { value: true });
// tslint:disable-next-line:no-var-requires
const PrinterBS = require('./Printer.bs');
exports.printCode = PrinterBS.printCode;
