/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const UtilsBS = require('./Utils.bs');

export const maskDots: (_1:string) => string = UtilsBS.maskDots;

export const unmaskDots: (_1:string) => string = UtilsBS.unmaskDots;
