// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as BookDisplayer from "./BookDisplayer.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as BooksOverviewQuery_graphql from "./__generated__/BooksOverviewQuery_graphql.bs.js";

var UseQuery = ReasonRelay.MakeUseQuery(/* module */[/* query */BooksOverviewQuery_graphql.node]);

var use = UseQuery[/* use */0];

function $$fetch(environment, variables) {
  return ReasonRelay.fetchQuery(environment, BooksOverviewQuery_graphql.node, variables);
}

var Query = /* module */[
  /* Operation */0,
  /* UseQuery */UseQuery,
  /* use */use,
  /* fetch */$$fetch
];

function BooksOverview(Props) {
  var query = Curry._3(use, /* () */0, /* StoreOrNetwork */2, /* () */0);
  if (typeof query === "number") {
    return React.createElement("div", undefined, "Loading...");
  } else if (query.tag) {
    return $$Array.mapi((function (index, book) {
                  return React.createElement("div", {
                              key: String(index)
                            }, React.createElement(BookDisplayer.make, {
                                  book: book
                                }), React.createElement("p", undefined, React.createElement("button", {
                                      onClick: (function (param) {
                                          return ReasonReactRouter.push("/book/" + book.id);
                                        })
                                    }, "More info")));
                }), query[0].books);
  } else {
    return React.createElement("div", undefined, "Error!");
  }
}

var make = BooksOverview;

export {
  Query ,
  make ,
  
}
/* UseQuery Not a pure module */
