// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as BookEditor from "./BookEditor.bs.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as ShelfDisplayer from "./ShelfDisplayer.bs.js";
import * as BookDisplayer_book_graphql from "./__generated__/BookDisplayer_book_graphql.bs.js";

var UseFragment = ReasonRelay.MakeUseFragment(/* module */[/* fragmentSpec */BookDisplayer_book_graphql.node]);

function use(fRef) {
  return Curry._1(UseFragment[/* use */0], fRef);
}

var BookFragment = /* module */[
  /* Operation */0,
  /* UseFragment */UseFragment,
  /* use */use
];

function BookDisplayer(Props) {
  var bookRef = Props.book;
  var match = Props.allowEditMode;
  var allowEditMode = match !== undefined ? match : false;
  var book = Curry._1(UseFragment[/* use */0], bookRef);
  var match$1 = React.useState((function () {
          return false;
        }));
  var setEditMode = match$1[1];
  var editMode = match$1[0];
  var match$2 = editMode && allowEditMode;
  return React.createElement("div", undefined, React.createElement("h1", undefined, book.title + (" " + book.author)), React.createElement(ShelfDisplayer.make, {
                  shelf: book.shelf
                }), allowEditMode ? React.createElement("p", undefined, React.createElement("button", {
                        onClick: (function (param) {
                            return Curry._1(setEditMode, (function (current) {
                                          return !current;
                                        }));
                          })
                      }, editMode ? "Stop editing" : "Start editing")) : null, React.createElement("p", undefined, match$2 ? React.createElement(BookEditor.make, {
                        book: book
                      }) : null));
}

var make = BookDisplayer;

export {
  BookFragment ,
  make ,
  
}
/* UseFragment Not a pure module */
