// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as CreateBookViewExistingBookDisplayer_book_graphql from "./__generated__/CreateBookViewExistingBookDisplayer_book_graphql.bs.js";

var UseFragment = ReasonRelay.MakeUseFragment(/* module */[/* fragmentSpec */CreateBookViewExistingBookDisplayer_book_graphql.node]);

function use(fRef) {
  return Curry._1(UseFragment[/* use */0], fRef);
}

var BookFragment = /* module */[
  /* Operation */0,
  /* UseFragment */UseFragment,
  /* use */use
];

function CreateBookViewExistingBookDisplayer(Props) {
  var bookRef = Props.book;
  var book = Curry._1(UseFragment[/* use */0], bookRef);
  return React.createElement("p", undefined, React.createElement("p", undefined, React.createElement("strong", undefined, book.title)), React.createElement("p", undefined, book.author));
}

var make = CreateBookViewExistingBookDisplayer;

export {
  BookFragment ,
  make ,
  
}
/* UseFragment Not a pure module */
