// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as RelayEnv from "./RelayEnv.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

function EnvironmentProvider(Props) {
  var children = Props.children;
  var match = Props.environment;
  var environment = match !== undefined ? Caml_option.valFromOption(match) : RelayEnv.environment;
  return React.createElement(ReasonRelay.Context[/* Provider */1][/* make */1], Curry._4(ReasonRelay.Context[/* Provider */1][/* makeProps */0], environment, children, undefined, /* () */0));
}

var make = EnvironmentProvider;

export {
  make ,
  
}
/* react Not a pure module */
