// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as RelayEnv from "./RelayEnv.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(ReasonRelay.Context[/* Provider */1][/* make */1], Curry._4(ReasonRelay.Context[/* Provider */1][/* makeProps */0], RelayEnv.environment, React.createElement(Main.make, { }), undefined, /* () */0)), "app");

export {
  
}
/*  Not a pure module */
