// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Fetch from "bs-fetch/src/Fetch.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Graphql_error = Caml_exceptions.create("RelayEnv.Graphql_error");

function fetchQuery(operation, variables, _cacheConfig) {
  return fetch("http://localhost:4000", Fetch.RequestInit[/* make */0](/* Post */2, {
                      "content-type": "application/json",
                      accept: "application/json"
                    }, Caml_option.some(JSON.stringify(Js_dict.fromList(/* :: */[
                                  /* tuple */[
                                    "query",
                                    operation.text
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "variables",
                                      variables
                                    ],
                                    /* [] */0
                                  ]
                                ]))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (resp) {
                if (resp.ok) {
                  return resp.json();
                } else {
                  return Promise.reject([
                              Graphql_error,
                              "Request failed: " + resp.statusText
                            ]);
                }
              }));
}

var network = ReasonRelay.Network[/* makePromiseBased */0](fetchQuery);

function makeEnvironment(param) {
  return ReasonRelay.Environment[/* make */0](network, ReasonRelay.Store[/* make */0](ReasonRelay.RecordSource[/* make */0](/* () */0)));
}

var environment = makeEnvironment(/* () */0);

export {
  Graphql_error ,
  fetchQuery ,
  network ,
  makeEnvironment ,
  environment ,
  
}
/* network Not a pure module */
