// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as ShelfDisplayer_shelf_graphql from "./__generated__/ShelfDisplayer_shelf_graphql.bs.js";

var UseFragment = ReasonRelay.MakeUseFragment(/* module */[/* fragmentSpec */ShelfDisplayer_shelf_graphql.node]);

function use(fRef) {
  return Curry._1(UseFragment[/* use */0], fRef);
}

var ShelfFragment = /* module */[
  /* Operation */0,
  /* UseFragment */UseFragment,
  /* use */use
];

function ShelfDisplayer(Props) {
  var shelfRef = Props.shelf;
  var shelf = Curry._1(UseFragment[/* use */0], shelfRef);
  return React.createElement("div", undefined, React.createElement("p", undefined, "on shelf: ", React.createElement("strong", undefined, shelf.name)));
}

var make = ShelfDisplayer;

export {
  ShelfFragment ,
  make ,
  
}
/* UseFragment Not a pure module */
