// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function ShowForDuration(Props) {
  var match = Props.duration;
  var duration = match !== undefined ? match : 200;
  var children = Props.children;
  var match$1 = React.useState((function () {
          return false;
        }));
  var setShow = match$1[1];
  var show = match$1[0];
  React.useEffect((function () {
          if (show) {
            var id = setTimeout((function (param) {
                    return Curry._1(setShow, (function (param) {
                                  return false;
                                }));
                  }), duration);
            return (function (param) {
                      clearTimeout(id);
                      return /* () */0;
                    });
          }
          
        }), /* array */[show]);
  React.useEffect((function () {
          Curry._1(setShow, (function (param) {
                  return true;
                }));
          return undefined;
        }), ([]));
  if (show) {
    return children;
  } else {
    return null;
  }
}

var make = ShowForDuration;

export {
  make ,
  
}
/* react Not a pure module */
