// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as BookDisplayer from "./BookDisplayer.bs.js";
import * as SingleBookDisplayerQuery_graphql from "./__generated__/SingleBookDisplayerQuery_graphql.bs.js";

var UseQuery = ReasonRelay.MakeUseQuery(/* module */[/* query */SingleBookDisplayerQuery_graphql.node]);

var use = UseQuery[/* use */0];

function $$fetch(environment, variables) {
  return ReasonRelay.fetchQuery(environment, SingleBookDisplayerQuery_graphql.node, variables);
}

var Query = /* module */[
  /* Operation */0,
  /* UseQuery */UseQuery,
  /* use */use,
  /* fetch */$$fetch
];

function SingleBookDisplayer(Props) {
  var bookId = Props.bookId;
  var query = Curry._3(use, {
        bookId: bookId
      }, /* StoreOrNetwork */2, /* () */0);
  if (typeof query === "number") {
    return React.createElement("div", undefined, "Loading...");
  } else if (query.tag) {
    var match = query[0].book;
    if (match == null) {
      return React.createElement("div", undefined, "404");
    } else {
      return React.createElement(BookDisplayer.make, {
                  book: match,
                  allowEditMode: true
                });
    }
  } else {
    return React.createElement("div", undefined, "Error!");
  }
}

var make = SingleBookDisplayer;

export {
  Query ,
  make ,
  
}
/* UseQuery Not a pure module */
