// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function toOpt(prim) {
  if (prim == null) {
    return undefined;
  } else {
    return Caml_option.some(prim);
  }
}

export {
  toOpt ,
  
}
/* No side effect */
