// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE


var Unions = /* module */[];

var node = ( {
  "kind": "Fragment",
  "name": "BookDisplayer_book",
  "type": "Book",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "title",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "author",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "shelf",
      "storageKey": null,
      "args": null,
      "concreteType": "Shelf",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "ShelfDisplayer_shelf",
          "args": null
        }
      ]
    },
    {
      "kind": "FragmentSpread",
      "name": "BookEditor_book",
      "args": null
    }
  ]
} );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
