// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE


var Unions = /* module */[];

var node = ( {
  "kind": "Fragment",
  "name": "CreateBookViewExistingBookDisplayer_book",
  "type": "Book",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "title",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "author",
      "args": null,
      "storageKey": null
    }
  ]
} );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
