// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE


var Unions = /* module */[];

var node = ( {
  "kind": "Fragment",
  "name": "ShelfDisplayer_shelf",
  "type": "Shelf",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "name",
      "args": null,
      "storageKey": null
    }
  ]
} );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
