// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE


function unwrap(wrapped) {
  var match = wrapped.__typename;
  switch (match) {
    case "Book" : 
        return /* `Book */[
                737456201,
                wrapped
              ];
    case "BookCollection" : 
        return /* `BookCollection */[
                -196012025,
                wrapped
              ];
    default:
      return /* UnmappedUnionMember */809179453;
  }
}

var Union_fromShelf = /* module */[/* unwrap */unwrap];

var Unions = /* module */[/* Union_fromShelf */Union_fromShelf];

var node = ( (function(){
var v0 = [
  {
    "kind": "LocalArgument",
    "name": "bookStatus",
    "type": "BookStatus!",
    "defaultValue": null
  },
  {
    "kind": "LocalArgument",
    "name": "shelfId",
    "type": "ID!",
    "defaultValue": null
  }
],
v1 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "id",
  "args": null,
  "storageKey": null
},
v2 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "title",
  "args": null,
  "storageKey": null
},
v3 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "status",
  "args": null,
  "storageKey": null
},
v4 = [
  (v1/*: any*/),
  (v2/*: any*/),
  (v3/*: any*/)
],
v5 = {
  "kind": "LinkedField",
  "alias": null,
  "name": "books",
  "storageKey": null,
  "args": [
    {
      "kind": "Variable",
      "name": "status",
      "variableName": "bookStatus"
    }
  ],
  "concreteType": "Book",
  "plural": true,
  "selections": (v4/*: any*/)
},
v6 = [
  {
    "kind": "Variable",
    "name": "shelfId",
    "variableName": "shelfId"
  }
],
v7 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "__typename",
  "args": null,
  "storageKey": null
},
v8 = {
  "kind": "InlineFragment",
  "type": "Book",
  "selections": (v4/*: any*/)
};
return {
  "kind": "Request",
  "fragment": {
    "kind": "Fragment",
    "name": "TestUnionsEnumsQuery",
    "type": "Query",
    "metadata": null,
    "argumentDefinitions": (v0/*: any*/),
    "selections": [
      (v5/*: any*/),
      {
        "kind": "LinkedField",
        "alias": null,
        "name": "fromShelf",
        "storageKey": null,
        "args": (v6/*: any*/),
        "concreteType": null,
        "plural": true,
        "selections": [
          (v7/*: any*/),
          (v8/*: any*/),
          {
            "kind": "InlineFragment",
            "type": "BookCollection",
            "selections": [
              (v1/*: any*/),
              {
                "kind": "LinkedField",
                "alias": null,
                "name": "books",
                "storageKey": null,
                "args": null,
                "concreteType": "Book",
                "plural": true,
                "selections": [
                  (v2/*: any*/),
                  (v3/*: any*/)
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "operation": {
    "kind": "Operation",
    "name": "TestUnionsEnumsQuery",
    "argumentDefinitions": (v0/*: any*/),
    "selections": [
      (v5/*: any*/),
      {
        "kind": "LinkedField",
        "alias": null,
        "name": "fromShelf",
        "storageKey": null,
        "args": (v6/*: any*/),
        "concreteType": null,
        "plural": true,
        "selections": [
          (v7/*: any*/),
          (v8/*: any*/),
          {
            "kind": "InlineFragment",
            "type": "BookCollection",
            "selections": [
              (v1/*: any*/),
              {
                "kind": "LinkedField",
                "alias": null,
                "name": "books",
                "storageKey": null,
                "args": null,
                "concreteType": "Book",
                "plural": true,
                "selections": [
                  (v2/*: any*/),
                  (v3/*: any*/),
                  (v1/*: any*/)
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "params": {
    "operationKind": "query",
    "name": "TestUnionsEnumsQuery",
    "id": null,
    "text": "query TestUnionsEnumsQuery(\n  $bookStatus: BookStatus!\n  $shelfId: ID!\n) {\n  books(status: $bookStatus) {\n    id\n    title\n    status\n  }\n  fromShelf(shelfId: $shelfId) {\n    __typename\n    ... on Book {\n      id\n      title\n      status\n    }\n    ... on BookCollection {\n      id\n      books {\n        title\n        status\n        id\n      }\n    }\n  }\n}\n",
    "metadata": {}
  }
};
})() );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
